<h2>Importing tensorflow</h2>


In [2]:
import tensorflow as tf

<h2>Building a graph</h2>

In [2]:
graph1 = tf.Graph()

In [4]:
with graph1.as_default():
    a = tf.constant([2], name = 'constant_a')
    b = tf.constant([3], name = 'constant_b')

<h4>To see the value of a we have to run the session</h4>

In [7]:
a

<tf.Tensor 'constant_a_1:0' shape=(1,) dtype=int32>

In [13]:
sess = tf.Session(graph = graph1)
result = sess.run(b)
print(result)


[3]


In [14]:
with graph1.as_default():
    c = tf.add(a,b)

In [15]:
result = sess.run(c)
print(result)

[5]


<h4>All data is passed between operations in a computation graph and these are passed in the form of tensor</h4>

<h2>Defining multidimensional array using Tensorflow</h2>

In [16]:
graph2 = tf.Graph()
with graph2.as_default():
    Scalar = tf.constant(2)
    Vector = tf.constant([5,6,2])
    Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    Tensor = tf.constant([[[1,2,3],[2,3,4],[3,4,5]],[[7,8,9],[8,9,10],[9,10,11]]])

with tf.Session(graph = graph2) as sess:
    result = sess.run(Scalar)
    print("Scalar (1 entry):\n %s \n" % result)
    result = sess.run(Vector)
    print("Vector (3 entries) : \n %s \n" % result)
    result = sess.run(Matrix)
    print("Matrix (3*3 entries) :\n %s \n" % result)
    result = sess.run(Tensor)
    print("Tensor (3*3*3) :\n %s \n" % result)
    
    

Scalar (1 entry):
 2 

Vector (3 entries) : 
 [5 6 2] 

Matrix (3*3 entries) :
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Tensor (3*3*3) :
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 



In [18]:
Tensor.shape

TensorShape([Dimension(2), Dimension(3), Dimension(3)])

In [20]:
Matrix.shape

TensorShape([Dimension(3), Dimension(3)])

In [21]:
Scalar.shape

TensorShape([])

In [22]:
Vector.shape

TensorShape([Dimension(3)])

<h3>Element wise multiplication(Hadamard product)

In [29]:
graph3 = tf.Graph()
with graph3.as_default():
    Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])
    
    add_1_operation = tf.add(Matrix_one,Matrix_two)
    add_2_operation = Matrix_one + Matrix_two
    
with tf.Session(graph = graph3) as sess:
    result  = sess.run(add_1_operation)
    print("Defined using Tensorflow function : ")
    print(result)
    result = sess.run(add_2_operation)
    print("Defined using normal expressions : ")
    print(result)

Defined using Tensorflow function : 
[[3 4 5]
 [4 5 6]
 [5 6 7]]
Defined using normal expressions : 
[[3 4 5]
 [4 5 6]
 [5 6 7]]


<h3>Regular matrix product

In [32]:
graph4 = tf.Graph()
with graph4.as_default():
    Matrix_one = tf.constant([[2,3],[3,4]])
    Matrix_two = tf.constant([[2,3],[3,4]])
    
    mul_opeartion = tf.matmul(Matrix_one , Matrix_two)
    
with tf.Session(graph = graph4) as sess:
    result = sess.run(mul_opeartion)
    print("Defined using Tensorflow function : ")
    print(result)

Defined using Tensorflow function : 
[[13 18]
 [18 25]]


<h3>Variables


In [39]:
v= tf.Variable(4)

In [41]:
update = tf.assign(v,v+1)


<h3>Intializing the variable before running the graph in session</h3>

<h4>Manipulating variables inside tensorflow graph</h4>

In [42]:
init_op = tf.global_variables_initializer()

In [43]:
with tf.Session() as session:
    session.run(init_op)
    print(session.run(v))
    for _ in range(3):
        session.run(update)
        print(session.run(v))

4
5
6
7


<h2>Placeholders(Feeding data outside of a tensorflow graph)</h2>

In [45]:
a = tf.placeholder(tf.float32)


In [58]:
b = a*2

<h5>As we created a hole so while running the session we have to pass a parameter</h5>

In [49]:
with tf.Session() as sess:
    result = sess.run(b,feed_dict = {a:3})
    print(result)

6.0


<h5>As in tensorflow data in stored in the form of multidimensional array so we can pass any kind of tensor through the placegolders</h5>

In [59]:
dictionary = {a: [[[1,2,3],[4,5,6],[7,8,9],[10,11,12]] , [[13,14,15],[16,17,18],[19,20,21],[22,23,24]]]}

with tf.Session() as sess:
    result = sess.run(b,feed_dict = dictionary)
    print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


<h2>Operation</h2>


In [63]:
graph5 = tf.Graph()
with graph5.as_default():
    a = tf.constant([5])
    b = tf.constant([2])
    c = tf.add(a,b)
    d = tf.subtract(b,b)
    
with tf.Session(graph = graph5) as sess:
    result = sess.run(c)
    print('c =: %s' % result)
    result = sess.run(d)
    print('d =: %s' % result)

c =: [7]
d =: [0]
